// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2023 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2021.3.20f1";
    extern const char* const UnityVersionDigits = "2021.3.20";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 20;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.3.20f1_577897200b8b";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.3.20f1_577897200b8b";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.3.20f1 (577897200b8b)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 5732503;

    extern const UInt64 UnityVersionDate = 1677107683;
    extern const char* const UnityVersionBranch = "2021.3/staging";
    extern const char* const UnityVersionDisplay = "2021.3.20f1";
    extern const char* const UnityVersionDisplay_Verbose = "2021.3.20f1.git.5732503";
    extern const char* const UnityVersionRevision = "577897200b8b";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.3.20f1 (577897200b8b)";
    extern const wchar_t* const L_UnityVersion = L"2021.3.20f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2023 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 20
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.3.20f1_577897200b8b"
    #define UNITY_VERSION_PARENS_HASH "2021.3.20f1 (577897200b8b)"
    #define UNITY_VERSION_BLD 5732503
    #define UNITY_VERSION_WIN "2021.3.20.5732503"

#endif // !RC_INVOKED
