using System.Collections;
using System.Collections.Generic;

public class GlobalVariable
{
    public static string[,] arrayLibraryButton =
    {
        {"Kangkung","icon/Icon_Kangkung"},
        {"Pokchoi","icon/Icon_Pokchoi"},
        {"Selada","icon/Icon_Selada"},
        {"Jagung","icon/Icon_Jagung"},
        {"Bawang","icon/Icon_Bawang"},
        {"Edamame","icon/Icon_Edamame"},
        {"Pepaya","icon/Icon_Payaya"},
        {"Pisang","icon/Icon_Pisang"},
        {"Lengkeng","icon/Icon_Lengkeng"},
        {"Rambutan","icon/Icon_Rambutan"},
        {"Jambu","icon/Icon_Jambu"},
        {"Padi","icon/Icon_Padi"},
        { "Pokchoi Siram Jamur", "icon/makanan/Makan_Pokchoi_Jamur"},
        { "Pokchoi Saus Tiram", "icon/makanan/Makan_Pokchoi_SausTiram"},
        { "Tumis Pakchoi Tahu", "icon/makanan/Makan_Pokchoi_Tahu"},

        { "Tumis Selada Jamur", "icon/makanan/Makan_Selada_TumisJamur"},
        { "Telur Dadar Selada","icon/makanan/Makan_Selada_TelurGulung"},

        { "Kangkung Tempe","icon/makanan/Makan_Kangkung_TumisTempe" },
        { "Cah Kangkung","icon/makanan/Makan_Kangkung_Tumis"},

        { "Jagung Bakar", "icon/makanan/Makan_Jagung_Bakar" },
        { "Tumis Jagung Bakar","icon/makanan/Makan_Jagung_Tumis" },
        { "Jagung Jamur Asam Manis","icon/makanan/Makan_Jagung_SiramJamur"},
        { "Sup Jagung","icon/makanan/Makan_Jagung_Sup"},

        { "Cincin Bawang","icon/makanan/Makan_Bawang_Goreng"},

        { "Tumis Edamame","icon/makanan/Makan_Edamame_Tumis"},
        { "Edamame Goreng","icon/makanan/Makan_Edamame_Goreng"},

        { "Nasi Goreng Edamame","icon/makanan/Makan_NasiGoreng_edamame"},
        { "Nasi Goreng Jagung","icon/makanan/Makan_NasiGoreng_Jagung"},

        { "Telur Rebus","icon/makanan/Makan_Telur_Rebus" },
        { "Telur Ceplok","icon/makanan/Makan_Telur_Ceplok" },
        { "Telur Dadar","icon/makanan/Makan_Telur_Gulung"},

        { "Nasi Goreng Lengkap","icon/makanan/Makan_NasiGoreng_Telur" }

    };
    public static string[,] arrayLibrary =
    {
        {"Kangkung", "icon/Icon_Kangkung","Kangkung adalah sejenis sayuran hijau yang populer di berbagai masakan, terutama di Asia Tenggara. Di beberapa negara, kangkung juga dikenal dengan sebutan \"water spinach\" atau \"morning glory\" dalam bahasa Inggris. Nama ilmiah dari kangkung adalah Ipomoea aquatica.\n\nManfaat kangkung contohnya: Kaya nutrisi\r\nMeningkatkan sistem kekebalan tubuh dengan vitamin C\r\nMenjaga keseyhatan tulang dengan kandungan vitamin K dan kalsium\r\nMenjaga kesehatan jantung dengan kandungan potasium\r\nMembantu proses pencernaan dengan kandungan serat\r\nMembantu kontrol berat badan dengan kandungan kalori yang rendah" },
        {"Pokchoi", "icon/Icon_Pokchoi","Pokchoi, juga dikenal sebagai bok choy atau sawi hijau, adalah jenis sayuran yang termasuk dalam keluarga kubis-kubisan atau Brassicaceae. Tanaman ini memiliki daun hijau gelap yang lebar dan tangkai putih yang berdaging. \nPokchoi biasanya tumbuh dalam bentuk daun bertingkat, di mana daun lebih besar tumbuh di bagian luar dan daun yang lebih kecil tumbuh di bagian dalam. Asal-usul pokchoi berasal dari Asia Timur, khususnya dari Cina, dan telah menjadi salah satu sayuran populer dalam masakan Asia. Saat ini, pokchoi juga banyak ditemukan dan digunakan dalam masakan di berbagai belahan dunia.\r\n\r\nPokchoi memiliki rasa yang ringan dan sedikit manis, serta tekstur yang renyah saat dimasak. Sayuran ini sangat serbaguna dan dapat dimasak dalam berbagai cara, seperti direbus, dikukus, ditumis, atau digunakan dalam sup dan hidangan panggang.\r\n\r\nKarena kandungan nutrisi yang kaya, pokchoi adalah sayuran yang sehat dan bermanfaat untuk tubuh. Ia kaya akan vitamin dan mineral seperti vitamin A, vitamin C, vitamin K, kalsium, zat besi, magnesium, dan serat, yang semuanya berkontribusi pada manfaat kesehatan yang beragam seperti mendukung kesehatan tulang, meningkatkan sistem kekebalan tubuh, dan menjaga kesehatan jantung dan kulit." },
        {"Selada", "icon/Icon_Selada","Selada adalah sejenis sayuran daun yang sering digunakan dalam berbagai hidangan dan salad. Sayuran ini memiliki daun hijau yang lembut dan renyah dengan bentuk dan ukuran yang bervariasi tergantung pada jenisnya. Selada berasal dari keluarga Asteraceae dan telah lama dibudidayakan sebagai sayuran. \n \n Selada merupakan sumber nutrisi yang baik, terutama vitamin A, vitamin C, dan serat. Ia rendah kalori sehingga cocok sebagai pilihan makanan sehat bagi mereka yang ingin menjaga berat badan atau sedang dalam program penurunan berat badan." },
        {"Jagung","icon/Icon_Jagung","Jagung adalah salah satu jenis sereal yang berasal dari tanaman Zea mays. Tanaman ini telah menjadi salah satu sumber makanan pokok di banyak negara, terutama di Amerika Selatan dan Amerika Tengah, serta bagian dari Afrika dan Asia. Buahnya yang biasa disebut \"pipi\" adalah bagian yang paling sering dikonsumsi, dan biasanya dimasak sebelum dimakan.\r\n\r\nManfaat jagung adalah sebagai berikut:\r\n\r\nSumber energi: Jagung adalah sumber karbohidrat yang kaya, yang memberikan energi bagi tubuh untuk beraktivitas.\r\n\r\nKaya serat: Jagung mengandung serat makanan yang membantu menjaga pencernaan yang sehat dan mengurangi risiko sembelit.\r\n\r\nKaya antioksidan: Jagung mengandung senyawa antioksidan seperti lutein dan zeaxanthin, yang penting untuk kesehatan mata dan mencegah penyakit degeneratif.\r\n\r\nSumber vitamin dan mineral: Jagung mengandung vitamin B kompleks, seperti tiamin, niacin, dan asam folat, serta mineral seperti fosfor dan magnesium.\r\n\r\nMenjaga kesehatan jantung: Serat dan beberapa senyawa dalam jagung dapat membantu mengurangi kadar kolesterol dan menjaga kesehatan jantung.\r\n\r\nMembantu pengaturan gula darah: Serat dalam jagung dapat membantu mengontrol kadar gula darah dan membantu mencegah lonjakan gula darah.\r\n\r\nSumber fitonutrien: Jagung mengandung fitonutrien seperti flavonoid dan karotenoid, yang berperan dalam menjaga kesehatan tubuh dan mencegah beberapa penyakit."},
        {"Bawang","icon/Icon_Bawang","Bawang merah (Allium cepa var. aggregatum) adalah salah satu jenis bawang yang memiliki bentuk lebih kecil dan warna kulit yang merah muda atau ungu. Bawang merah memiliki rasa yang lebih manis dan ringan dibandingkan dengan bawang putih, sehingga sering digunakan dalam masakan sebagai bumbu atau penyedap.\r\n\r\nManfaat adalah sebagai berikut:\r\n\r\nKandungan nutrisi: Bawang merah mengandung vitamin C, vitamin B6, serat, dan antioksidan, yang semuanya bermanfaat untuk kesehatan tubuh.\r\n\r\nMenjaga kesehatan jantung: Bawang merah mengandung quercetin, senyawa antioksidan yang dapat membantu menjaga kesehatan jantung dan mengurangi risiko penyakit kardiovaskular.\r\n\r\nMengurangi peradangan: Senyawa sulfur dalam bawang merah memiliki sifat anti-inflamasi yang dapat membantu mengurangi peradangan dalam tubuh.\r\n\r\nMengatur gula darah: Bawang merah dapat membantu meningkatkan sensitivitas insulin dan mengatur kadar gula darah, sehingga bermanfaat bagi penderita diabetes.\r\n\r\nMenjaga kesehatan tulang: Bawang merah mengandung kalsium dan vitamin K, yang berperan dalam menjaga kepadatan tulang dan mencegah risiko osteoporosis.\r\n\r\nMenjaga kesehatan kulit: Kandungan vitamin C dalam bawang merah berperan sebagai antioksidan untuk melawan kerusakan radikal bebas dan menjaga kesehatan kulit.\r\n\r\nMeningkatkan sistem kekebalan tubuh: Vitamin C dan antioksidan dalam bawang merah membantu meningkatkan daya tahan tubuh terhadap infeksi.\r\n\r\nMenyediakan nutrisi penting: Bawang merah adalah sumber serat dan vitamin yang penting untuk fungsi tubuh yang optimal."},
        {"Edamame","icon/Icon_Edamame","Edamame adalah jenis kacang kedelai yang masih muda dan masih berada dalam polongnya. Biasanya, edamame diolah dan dimakan sebagai makanan ringan atau hidangan pembuka. Makanan ini populer dalam masakan Jepang dan telah menjadi semakin terkenal di berbagai belahan dunia karena manfaat kesehatannya.\r\n\r\nManfaat edamame adalah sebagai berikut:\r\n\r\nSumber protein nabati: Edamame adalah sumber protein nabati yang baik, sehingga cocok untuk menjadi alternatif bagi orang yang mengikuti diet vegetarian atau vegan.\r\n\r\nTinggi serat: Edamame mengandung serat makanan yang membantu menjaga kesehatan pencernaan, mengurangi kadar kolesterol, dan mengatur gula darah.\r\n\r\nKaya akan vitamin dan mineral: Edamame mengandung vitamin B kompleks, vitamin C, vitamin K, serta mineral seperti zat besi, magnesium, fosfor, dan kalium.\r\n\r\nAntioksidan: Edamame mengandung senyawa antioksidan seperti isoflavon, yang membantu melawan radikal bebas dan melindungi sel-sel tubuh dari kerusakan.\r\n\r\nMenjaga kesehatan jantung: Kombinasi serat, protein, dan antioksidan dalam edamame dapat membantu menjaga kesehatan jantung dan mengurangi risiko penyakit kardiovaskular.\r\n\r\nMeningkatkan sistem kekebalan tubuh: Vitamin C dalam edamame berperan dalam meningkatkan sistem kekebalan tubuh dan membantu tubuh melawan infeksi.\r\n\r\nMenjaga kesehatan tulang: Edamame mengandung vitamin K dan kalsium, yang penting untuk menjaga kepadatan tulang dan mencegah risiko osteoporosis.\r\n\r\nMenyediakan energi: Edamame mengandung karbohidrat kompleks, yang menyediakan energi tahan lama bagi tubuh."},
        {"Pepaya","icon/Icon_Payaya","Pepaya adalah sebuah buah yang berasal dari tanaman Carica papaya. Buah pepaya memiliki bentuk yang panjang, biasanya berwarna hijau atau oranye ketika matang. Dagingnya berwarna oranye, kuning, atau merah tergantung pada varietasnya. Pepaya tumbuh di banyak wilayah tropis dan subtropis di seluruh dunia, dan telah menjadi salah satu buah yang populer di banyak negara.\r\n\r\nManfaat pepaya adalah sebagai berikut:\r\n\r\nSumber vitamin C: Pepaya mengandung vitamin C yang tinggi, yang membantu meningkatkan sistem kekebalan tubuh dan melindungi tubuh dari infeksi.\r\n\r\nSumber vitamin A: Buah pepaya kaya akan beta-karoten, yang akan diubah menjadi vitamin A dalam tubuh, dan penting untuk kesehatan mata dan kulit.\r\n\r\nPencernaan yang baik: Pepaya mengandung enzim papain yang dapat membantu memecah protein dan membantu pencernaan.\r\n\r\nKaya serat: Pepaya mengandung serat yang baik untuk pencernaan dan membantu menjaga kesehatan saluran pencernaan.\r\n\r\nAntioksidan: Pepaya mengandung senyawa antioksidan seperti likopen dan beta-karoten yang membantu melawan radikal bebas dan mencegah kerusakan sel.\r\n\r\nMenjaga kesehatan kulit: Nutrisi dalam pepaya membantu menjaga kulit sehat dan bercahaya.\r\n\r\nMenjaga kesehatan jantung: Pepaya mengandung kalium, yang membantu menjaga tekanan darah normal dan kesehatan jantung.\r\n\r\nRendah kalori: Pepaya adalah buah rendah kalori, sehingga cocok untuk mereka yang ingin menjaga berat badan atau mengontrol asupan kalori."},
        {"Pisang","icon/Icon_Pisang","Pisang adalah salah satu jenis buah yang sangat populer dan sering dikonsumsi di seluruh dunia. Buah ini berasal dari tanaman pisang, yang termasuk dalam keluarga Musaceae. Pisang memiliki kulit yang tipis dan mudah dikupas, serta daging yang lembut dan manis.\r\n\r\nCiri khas pisang adalah bentuknya yang panjang dan melengkung dengan berbagai ukuran, warna, dan tingkat kematangan. Buah pisang dapat berwarna hijau, kuning, atau bahkan merah tergantung pada varietasnya dan tingkat kematangannya.\r\n\r\nManfaat pisang secara singkat adalah sebagai berikut:\r\n\r\nSumber energi: Pisang kaya akan karbohidrat, terutama dalam bentuk gula alami seperti glukosa, fruktosa, dan sukrosa, yang menyediakan energi bagi tubuh.\r\n\r\nKaya serat: Pisang mengandung serat makanan, yang membantu menjaga pencernaan yang sehat dan mengurangi risiko sembelit.\r\n\r\nSumber vitamin dan mineral: Pisang mengandung vitamin B6, vitamin C, potassium, magnesium, dan vitamin B kompleks lainnya, yang semuanya berperan dalam menjaga kesehatan tubuh.\r\n\r\nMenjaga kesehatan jantung: Kandungan potassium dalam pisang membantu menjaga keseimbangan tekanan darah dan mendukung kesehatan jantung.\r\n\r\nMenjaga kesehatan otot: Pisang mengandung magnesium, yang penting untuk fungsi otot dan kontraksi yang sehat.\r\n\r\nMeningkatkan suasana hati: Pisang mengandung tryptophan, yang dapat meningkatkan produksi hormon bahagia serotonin dalam otak, membantu mengurangi stres dan meningkatkan suasana hati.\r\n\r\nMenyediakan antioksidan: Pisang mengandung senyawa antioksidan seperti dopamin dan katekin, yang membantu melawan radikal bebas dan melindungi sel-sel tubuh dari kerusakan."},
        {"Lengkeng","icon/Icon_Lengkeng","Lengkeng adalah buah dari tanaman Dimocarpus longan, yang termasuk dalam keluarga Sapindaceae. Buah lengkeng memiliki kulit tipis dan cokelat yang melindungi daging buah yang berair dan manis. Dalam daging buah lengkeng terdapat biji yang tidak dapat dimakan dan harus dibuang sebelum mengonsumsi buah ini.\r\n\r\nBuah lengkeng berasal dari daerah tropis dan subtropis di Asia, terutama di negara-negara seperti China, Thailand, Vietnam, dan Indonesia. Buah lengkeng biasanya dikonsumsi segar sebagai buah makanan ringan atau diolah menjadi berbagai hidangan seperti salad, dessert, atau minuman.\r\n\r\nManfaat lengkeng secara singkat adalah sebagai berikut:\r\n\r\nSumber vitamin dan mineral: Lengkeng mengandung vitamin C, vitamin A, vitamin B kompleks, potassium, magnesium, dan zat besi, yang berperan dalam menjaga kesehatan tubuh.\r\n\r\nAntioksidan: Lengkeng mengandung senyawa flavonoid dan antioksidan, yang membantu melawan radikal bebas dan mencegah kerusakan sel.\r\n\r\nMenjaga kesehatan kulit: Kandungan vitamin C dalam lengkeng berperan dalam produksi kolagen, membantu menjaga kulit tetap sehat dan bercahaya.\r\n\r\nSumber energi: Lengkeng mengandung karbohidrat yang menyediakan energi bagi tubuh.\r\n\r\nMenjaga kesehatan mata: Kandungan vitamin A dan antioksidan dalam lengkeng bermanfaat untuk kesehatan mata dan penglihatan yang baik.\r\n\r\nMeningkatkan sistem kekebalan tubuh: Vitamin C dalam lengkeng membantu meningkatkan sistem kekebalan tubuh dan membantu tubuh melawan infeksi.\r\n\r\nMenjaga kesehatan jantung: Potassium dalam lengkeng membantu menjaga keseimbangan tekanan darah dan mendukung kesehatan jantung."},
        {"Rambutan","icon/Icon_Rambutan","Rambutan adalah sejenis buah yang berasal dari pohon rambutan (Nephelium lappaceum) yang termasuk dalam keluarga Sapindaceae. Buah ini sangat populer di wilayah tropis dan subtropis, terutama di negara-negara Asia Tenggara, seperti Indonesia, Thailand, dan Malaysia.\r\n\r\nBuah rambutan memiliki kulit berduri yang tebal dan berwarna hijau atau merah tergantung pada tingkat kematangannya. Daging buah rambutan yang manis dan berair berada di dalam kulit, dan biasanya ada biji besar di tengahnya yang tidak dapat dimakan dan harus dibuang sebelum mengonsumsi buah ini.\r\n\r\nManfaat rambutan secara singkat adalah sebagai berikut:\r\n\r\nSumber vitamin C: Rambutan mengandung vitamin C yang tinggi, yang membantu meningkatkan sistem kekebalan tubuh dan melindungi tubuh dari infeksi.\r\n\r\nSumber antioksidan: Rambutan mengandung senyawa flavonoid dan antioksidan, seperti katekin dan epikatekin, yang membantu melawan radikal bebas dan melindungi sel-sel tubuh dari kerusakan.\r\n\r\nMenjaga kesehatan kulit: Kandungan vitamin C dalam rambutan berperan dalam produksi kolagen, membantu menjaga kulit tetap sehat dan bercahaya.\r\n\r\nMenjaga kesehatan mata: Rambutan mengandung vitamin A dan senyawa seperti beta-karoten, yang bermanfaat untuk kesehatan mata dan penglihatan yang baik.\r\n\r\nSumber energi: Rambutan mengandung karbohidrat, yang menyediakan energi bagi tubuh.\r\n\r\nMenjaga kesehatan tulang: Rambutan mengandung mineral seperti potassium, kalsium, dan magnesium, yang berperan dalam menjaga kepadatan tulang.\r\n\r\nMeningkatkan pencernaan: Rambutan mengandung serat makanan, yang membantu menjaga kesehatan saluran pencernaan dan mencegah sembelit."},
        {"Jambu","icon/Icon_Jambu","Jambu kristal adalah salah satu varietas buah jambu yang memiliki ciri khas biji yang bening seperti kristal, itulah mengapa disebut jambu kristal. Nama ilmiahnya adalah Psidium guajava. Buah ini juga dikenal dengan sebutan jambu biji atau jambu kaca. Jambu kristal memiliki kulit yang berwarna hijau kekuningan dan daging buah yang bening, renyah, dan manis dengan biji-biji yang hampir transparan.\r\n\r\nBuah jambu kristal memiliki rasa yang manis dan segar, serta tekstur yang renyah, membuatnya menjadi favorit banyak orang sebagai buah makanan ringan atau dijadikan bagian dalam hidangan, salad, atau jus.\r\n\r\nManfaat jambu kristal secara singkat adalah sebagai berikut:\r\n\r\nSumber vitamin C: Jambu kristal mengandung vitamin C yang tinggi, yang membantu meningkatkan sistem kekebalan tubuh dan melindungi tubuh dari infeksi.\r\n\r\nKaya serat: Jambu kristal mengandung serat makanan yang membantu menjaga kesehatan pencernaan dan mengurangi risiko sembelit.\r\n\r\nMenjaga kesehatan kulit: Kandungan vitamin C dalam jambu kristal berperan sebagai antioksidan untuk melawan kerusakan radikal bebas dan menjaga kulit tetap sehat.\r\n\r\nMenjaga kesehatan mata: Jambu kristal mengandung vitamin A dan senyawa seperti beta-karoten, yang baik untuk kesehatan mata dan penglihatan yang baik.\r\n\r\nSumber energi: Jambu kristal mengandung karbohidrat, yang menyediakan energi bagi tubuh.\r\n\r\nMenjaga kesehatan jantung: Jambu kristal mengandung potassium, yang membantu menjaga keseimbangan tekanan darah dan mendukung kesehatan jantung.\r\n\r\nMengandung antioksidan: Jambu kristal mengandung senyawa antioksidan yang membantu melawan radikal bebas dan mencegah kerusakan sel."},
        {"Padi","icon/Icon_Padi","Padi (Oryza sativa) adalah salah satu tanaman sereal utama yang merupakan makanan pokok bagi sebagian besar penduduk dunia, terutama di wilayah Asia. Padi adalah jenis tanaman yang ditanam di lahan sawah atau tambak dengan menggunakan teknik pertanian yang disebut pertanian padi.\r\n\r\nPadi memiliki batang panjang dan daun yang lebar. Bulir-bulir padi tumbuh di bagian atas tanaman dalam kelompok yang disebut malai. Setelah panen, bulir padi diolah menjadi beras yang merupakan sumber utama karbohidrat bagi banyak orang di dunia.\r\n\r\nPadi tumbuh di berbagai wilayah yang memiliki iklim tropis dan subtropis dengan suhu dan curah hujan yang cukup. Pertanian padi membutuhkan air yang cukup, sehingga banyak daerah yang menggunakan sistem irigasi atau pengairan untuk menanam padi.\r\n\r\nPadi memiliki peran penting dalam menyediakan makanan bagi masyarakat global dan menjadi tulang punggung pangan bagi miliaran orang di dunia. Olahannya yang berupa beras juga menjadi bahan makanan dasar dalam banyak hidangan tradisional dan modern di berbagai negara, seperti nasi goreng, nasi putih, sushi, dan banyak lagi.\r\n\r\nSelain sebagai sumber karbohidrat, padi juga memiliki peran penting dalam ekonomi dan budaya di banyak negara, terutama di Asia, di mana pertanian padi menjadi bagian tak terpisahkan dari kehidupan masyarakat."},
    { "Pokchoi Siram Jamur", "icon/makanan/Makan_Pokchoi_Jamur", "Pokchoi tumis jamur adalah hidangan masakan yang melibatkan memasak pokchoi (juga dikenal sebagai bok choy atau pak choi) dan jamur dengan teknik tumis. Pokchoi (Bok Choy atau Pak Choi): Pokchoi adalah jenis sayuran yang berasal dari keluarga Brassicaceae, yang juga mencakup kubis dan brokoli. Biasanya memiliki batang yang lebar dan daun yang hijau. Terdapat dua varietas utama dari pokchoi: varietas dengan daun yang lebih besar dan varietas dengan daun yang lebih kecil. Pokchoi biasanya digunakan dalam masakan Asia, terutama dalam hidangan Tiongkok. Jamur: Jamur adalah bahan makanan yang sering digunakan dalam masakan untuk memberikan cita rasa dan tekstur yang unik. Jenis jamur yang digunakan dalam \"pokchoi tumis jamur\" bisa bermacam-macam, seperti jamur kuping, jamur shiitake, atau jamur kancing. Tumis adalah teknik memasak yang melibatkan memasak bahan-bahan dengan cepat di atas panas tinggi dengan sedikit minyak. Biasanya, pokchoi dan jamur akan dipotong-potong dan ditumis bersama-sama dengan bumbu-bumbu seperti bawang putih, bawang merah, saus kecap, dan saus jamur. Proses tumis ini memberikan rasa gurih dan renyah pada bahan-bahan. Hasil akhir \"pokchoi tumis jamur\" adalah hidangan yang menggabungkan rasa gurih dari jamur dengan kesegaran dan kelembutan pokchoi. Hidangan ini umumnya disajikan sebagai lauk pendamping nasi atau mi, dan bisa dimodifikasi dengan menambahkan bahan-bahan lain sesuai selera, seperti tahu, daging, atau sayuran lainnya."},
        { "Pokchoi Saus Tiram", "icon/makanan/Makan_Pokchoi_SausTiram","Pokchoi saus tiram mengacu pada hidangan masakan yang menggunakan pokchoi (juga dikenal sebagai bok choy atau pak choi) dan saus tiram sebagai bahan utama.\nBahan bahan yang digunakan dalam pokchoi saus tiram adalah sebagai berikut:\n\n1. **Pokchoi (Bok Choy atau Pak Choi):** Pokchoi adalah jenis sayuran yang berasal dari keluarga Brassicaceae, yang juga mencakup kubis dan brokoli. Biasanya memiliki batang yang lebar dan daun yang hijau. Terdapat dua varietas utama dari pokchoi: varietas dengan daun yang lebih besar dan varietas dengan daun yang lebih kecil. Pokchoi biasanya digunakan dalam masakan Asia, terutama dalam hidangan Tiongkok.\n\n2. **Saus Tiram:** Saus tiram adalah saus yang terbuat dari air tiram yang difermentasi, garam, dan beberapa bahan tambahan seperti minyak wijen, kecap asin, dan bumbu lainnya. Saus ini memiliki rasa gurih dan asin yang khas, serta digunakan sebagai bumbu dalam masakan Tiongkok dan Asia Timur lainnya. Saus tiram sering digunakan untuk memberi rasa pada berbagai jenis hidangan, termasuk sayuran dan daging.\n\n Proses memasak biasanya melibatkan merendam pokchoi dalam air panas, kemudian menggorengnya dengan sedikit minyak, bawang putih, dan saus tiram. Hasilnya adalah hidangan yang kaya rasa, dengan pokchoi yang renyah dan terasa gurih dari saus tiram.\n\nHidangan ini umumnya dihidangkan sebagai lauk pendamping nasi atau mi, dan dapat dimodifikasi dengan menambahkan bahan-bahan lain seperti jamur, wortel, atau daging sesuai selera."
        },
        { "Tumis Pakchoi Tahu", "icon/makanan/Makan_Pokchoi_Tahu","\"Pakchoi tumis tahu\" adalah hidangan masakan yang menggabungkan pakchoi (juga dikenal sebagai bok choy atau pak choi) dan tahu dengan teknik tumis.\r\n\r\n    Pakchoi (Bok Choy atau Pak Choi): Pakchoi adalah jenis sayuran yang berasal dari keluarga Brassicaceae, yang juga mencakup kubis dan brokoli. Pakchoi memiliki batang yang lebar dan daun yang hijau. Varian-varian pakchoi memiliki perbedaan ukuran daun. Sayuran ini umumnya digunakan dalam masakan Asia, terutama masakan Tiongkok.\r\n\r\n    Tahu: Tahu adalah produk makanan yang terbuat dari kedelai. Tahu umumnya berbentuk padat dan memiliki rasa yang netral, sehingga sering digunakan sebagai bahan dasar untuk berbagai hidangan. Dalam \"pakchoi tumis tahu\", tahu akan menjadi bahan tambahan yang dicampur dengan pakchoi.\r\n\r\nProses memasak \"pakchoi tumis tahu\" melibatkan memotong-motong pakchoi dan tahu menjadi potongan-potongan kecil, kemudian menumisnya dengan minyak dan bumbu-bumbu. Bumbu-bumbu yang digunakan dapat beragam, seperti bawang putih, bawang merah, saus tiram, saus kecap, atau bumbu lain sesuai selera. Tofu (tahu) juga bisa ditambahkan untuk memberikan tekstur dan protein pada hidangan.\r\n\r\nHasil akhirnya adalah hidangan yang menggabungkan kelembutan pakchoi dengan rasa dan tekstur tahu yang renyah. \"Pakchoi tumis tahu\" sering disajikan sebagai lauk pendamping nasi atau mi, dan dapat dimodifikasi dengan tambahan bahan-bahan lain sesuai selera, seperti sayuran lain, jamur, atau bahan protein lainnya."},
        
        { "Tumis Selada Jamur", "icon/makanan/Makan_Selada_TumisJamur", "\"Selada tumis jamur\" adalah hidangan masakan yang melibatkan memasak selada dan jamur dengan teknik tumis.\r\n\r\n    Selada: Selada adalah jenis sayuran daun yang umumnya digunakan dalam berbagai jenis salad dan hidangan lainnya. Ada berbagai varietas selada, termasuk selada hijau, selada merah, dan selada romaine. Selada memiliki rasa segar dan tekstur renyah.\r\n\r\n    Jamur: Jamur adalah bahan makanan yang sering digunakan dalam masakan untuk memberikan cita rasa dan tekstur yang unik. Dalam \"selada tumis jamur\", jamur akan menjadi bahan utama yang dicampur dengan selada.\r\n\r\nTumis adalah teknik memasak yang melibatkan memasak bahan-bahan dengan cepat di atas panas tinggi dengan sedikit minyak. Dalam \"selada tumis jamur\", selada dan jamur akan ditumis bersama-sama dengan bumbu-bumbu seperti bawang putih, bawang merah, saus kecap, atau saus jamur. Proses tumis ini memberikan rasa gurih dan renyah pada bahan-bahan.\r\n\r\nHasil akhir \"selada tumis jamur\" adalah hidangan yang menggabungkan rasa segar dari selada dengan cita rasa jamur yang khas. Hidangan ini umumnya disajikan sebagai lauk pendamping nasi atau mi, atau bisa juga dihidangkan sebagai hidangan sendiri dengan tambahan bahan-bahan lain sesuai selera, seperti bawang goreng atau biji wijen."},
        { "Telur Dadar Selada","icon/makanan/Makan_Selada_TelurGulung","\"Telur dadar selada\" adalah hidangan yang terbuat dari telur yang dikocok dan dicampur dengan selada, kemudian dimasak menjadi dadar (telur dadar) dengan teknik penggorengan.\r\n\r\n    Telur Dadar: Telur dadar adalah hidangan yang dibuat dengan mengocok telur dan mencampurnya dengan bahan-bahan lain, lalu memasak campuran telur tersebut di atas wajan atau penggorengan. Ini adalah hidangan yang umum di banyak budaya dan dapat dimodifikasi dengan berbagai bahan tambahan.\r\n\r\n    Selada: Selada adalah jenis sayuran daun yang umumnya digunakan dalam salad atau hidangan lainnya. Selada memiliki rasa segar dan tekstur renyah, membuatnya menjadi bahan yang umum digunakan dalam hidangan seperti telur dadar selada.\r\n\r\n\"Telur dadar selada\" melibatkan mengocok telur dan mencampurnya dengan potongan-potongan selada. Bumbu-bumbu seperti garam, lada, atau bumbu lainnya juga dapat ditambahkan sesuai selera. Campuran telur dan selada ini kemudian dimasak di atas penggorengan hingga matang dan berbentuk dadar.\r\n\r\nHasil akhir \"telur dadar selada\" adalah dadar yang memiliki rasa telur yang lezat dan dipadukan dengan kesegaran serta renyahnya selada. Hidangan ini dapat disajikan sebagai lauk pendamping nasi atau roti, atau bahkan sebagai hidangan utama. Banyak variasi dalam resep telur dadar selada yang mungkin mencakup tambahan bahan seperti bawang, keju, dan bahan lainnya sesuai selera."},

        { "Kangkung Tempe","icon/makanan/Makan_Kangkung_TumisTempe","\"Kangkung tumis tempe\" adalah hidangan masakan yang melibatkan memasak kangkung dan tempe dengan teknik tumis.\r\n\r\n    Kangkung: Kangkung adalah jenis sayuran air yang sering digunakan dalam masakan Asia, terutama di Indonesia. Daun dan batang kangkung biasanya digunakan dalam masakan, dan memiliki rasa yang segar dan renyah setelah dimasak.\r\n\r\n    Tempe: Tempe adalah produk pangan yang berasal dari fermentasi kedelai. Ini adalah sumber protein yang umum dalam masakan Indonesia dan Asia Tenggara. Tempe memiliki rasa gurih dan konsistensi padat.\r\n\r\nDalam \"kangkung tumis tempe,\" kangkung dan tempe biasanya dipotong-potong dan dimasak bersama-sama dengan teknik tumis. Proses tumis melibatkan memasak bahan-bahan dengan cepat di atas panas tinggi dengan sedikit minyak. Kangkung dan tempe ditumis dengan bumbu-bumbu seperti bawang putih, cabai, saus kecap, atau saus lainnya.\r\n\r\nHasil akhir \"kangkung tumis tempe\" adalah hidangan yang menggabungkan rasa segar dan renyah dari kangkung dengan rasa gurih dan padat dari tempe. Hidangan ini sering disajikan sebagai lauk pendamping nasi dalam masakan Indonesia, dan dapat dimodifikasi dengan tambahan bumbu atau bahan lain sesuai selera." },
        { "Cah Kangkung","icon/makanan/Makan_Kangkung_Tumis","\"Cah kangkung\" adalah hidangan masakan Tiongkok yang terkenal dan populer. Nama \"cah kangkung\" secara harfiah berarti \"kangkung sauté\" dalam bahasa Indonesia. Ini adalah hidangan yang melibatkan memasak kangkung dengan cepat menggunakan teknik sauté (tumis) dan bumbu-bumbu yang khas.\r\n\r\nKangkung: Kangkung adalah jenis sayuran air yang sering digunakan dalam masakan Asia. Daun dan batang kangkung biasanya digunakan dalam masakan. Kangkung memiliki rasa yang segar dan renyah, dan biasanya digunakan sebagai bahan dalam hidangan ini.\r\n\r\n    Cara Memasak: Dalam \"cah kangkung,\" kangkung dicuci bersih dan daun serta batangnya dipotong-potong. Proses memasak dimulai dengan menumis bumbu-bumbu seperti bawang putih, cabai merah, dan bumbu-bumbu lainnya di atas wajan dengan minyak panas. Setelah bumbu-bumbu harum, kangkung ditambahkan dan dicampur dengan bumbu-bumbu. Proses ini sangat cepat sehingga kangkung tidak terlalu matang dan masih mempertahankan kelembutan dan kecrispy-an.\r\n\r\n    Rasa dan Penyajian: \"Cah kangkung\" memiliki rasa yang gurih, segar, dan sedikit pedas karena kehadiran bumbu-bumbu yang digunakan. Hidangan ini sering kali dihidangkan sebagai lauk pendamping nasi putih, nasi goreng, atau mi. Beberapa variasi mungkin juga menambahkan bahan-bahan lain seperti udang, daging ayam, atau tahu.\r\n\r\n    Populeritas: \"Cah kangkung\" adalah hidangan yang populer di berbagai restoran masakan Tiongkok di seluruh dunia, serta di rumah-rumah di Asia Tenggara. Ini adalah salah satu hidangan yang sederhana tetapi lezat dalam masakan Tiongkok dan populer karena cita rasanya yang khas.\r\n\r\nHidangan \"cah kangkung\" sering menjadi pilihan yang populer bagi mereka yang menginginkan hidangan sayuran segar dan lezat dengan sentuhan rasa pedas dan gurih."},

        { "Jagung Bakar", "icon/makanan/Makan_Jagung_Bakar","\"Jagung bakar\" adalah hidangan yang terbuat dari jagung yang dimasak dengan cara dipanggang atau dibakar hingga kulit luar jagung menjadi garing dan berwarna kecokelatan.\r\n\r\n    Jagung: Jagung adalah tanaman serealia yang menghasilkan biji-bijian yang umumnya dikenal dengan nama jagung manis. Biji jagung tersebut dapat dimakan dalam berbagai bentuk dan direbus atau dipanggang. Dalam hidangan \"jagung bakar,\" ciri khasnya adalah jagung tersebut dipanggang dengan atau tanpa kulit luar.\r\n\r\n    Cara Memasak: Dalam pembuatan \"jagung bakar,\" jagung yang masih dalam daunnya biasanya direndam dalam air terlebih dahulu selama beberapa waktu. Kemudian, jagung tersebut dapat dibakar langsung di atas api terbuka atau di atas panggangan yang dipanaskan. Proses pemanggangan menyebabkan kulit luar jagung menjadi garing dan menghitam, sementara biji jagung di dalamnya tetap matang dan lezat.\r\n\r\n    Rasa dan Penyajian: Jagung bakar memiliki rasa yang khas karena proses pemanggangan yang memberikan aroma dan cita rasa yang berbeda dari jagung yang direbus atau dimasak dengan cara lain. Kulit luar jagung yang garing seringkali memberikan sensasi renyah saat dikunyah, sementara biji jagungnya tetap lezat dan manis. Beberapa orang menambahkan bumbu atau mentega pada jagung bakar setelah proses pemanggangan untuk memberikan cita rasa tambahan.\r\n\r\n    Variasi: Ada berbagai variasi dalam hidangan jagung bakar. Beberapa mungkin menghilangkan kulit luar jagung untuk menghadirkan biji jagung yang terbuka dan lebih mudah diakses. Ada juga variasi yang menambahkan bumbu khusus atau saus untuk meningkatkan rasa dan aroma.\r\n\r\n    Populeritas: Jagung bakar adalah hidangan populer dalam berbagai budaya di seluruh dunia, terutama di acara-acara luar ruangan, pesta, atau festival. Di beberapa negara, jagung bakar bahkan menjadi hidangan khas musim panas yang sangat dinanti-nantikan.\r\n\r\nHidangan \"jagung bakar\" adalah hidangan yang sederhana tetapi memiliki rasa dan aroma yang khas, dan sering kali dianggap sebagai hidangan yang lezat untuk dinikmati di luar ruangan." },
        { "Tumis Jagung Bakar","icon/makanan/Makan_Jagung_Tumis","Tumis jagung bakar adalah hidangan yang terbuat dari jagung yang dibakar, kemudian ditumis dengan bawang bombay, bawang putih, paprika, dan bumbu lainnya. Tumis jagung bakar biasanya disajikan sebagai lauk atau makanan ringan.\r\n\r\nTumis jagung bakar adalah hidangan yang mudah dibuat dan lezat. Hidangan ini dapat dibuat dengan bahan-bahan yang mudah ditemukan di dapur." },
        { "Jagung Jamur Asam Manis","icon/makanan/Makan_Jagung_SiramJamur","Jagung tumis jamur asam manis adalah hidangan masakan yang menggabungkan jagung, jamur, dan saus asam manis melalui teknik tumis. \r\n\r\n    Jagung: Jagung adalah tanaman serealia yang menghasilkan biji-bijian yang umum dikonsumsi. Dalam hidangan ini, jagung biasanya digunakan dalam bentuk biji jagung yang dipotong dari tongkolnya.\r\n\r\n    Jamur: Jamur adalah bahan makanan yang sering digunakan dalam masakan untuk memberikan cita rasa dan tekstur yang unik. Jenis jamur yang digunakan dalam \"jagung tumis jamur asam manis\" bisa bermacam-macam, seperti jamur kancing, jamur tiram, atau jenis jamur lainnya.\r\n\r\n    Saus Asam Manis: Saus asam manis adalah saus yang mencampurkan rasa asam dan manis. Umumnya, saus ini terbuat dari campuran bahan seperti cuka, gula, saus tomat, dan beberapa bumbu lainnya. Saus asam manis sering digunakan dalam masakan Asia dan Tiongkok.\r\n\r\nDalam \"jagung tumis jamur asam manis,\" jagung dan jamur biasanya dipotong-potong dan dimasak menggunakan teknik tumis. Proses tumis melibatkan memasak bahan-bahan dengan cepat di atas panas tinggi dengan sedikit minyak. Setelah jagung dan jamur ditumis hingga matang, saus asam manis ditambahkan ke dalam hidangan dan dicampur bersama-sama.\r\n\r\nHasil akhir \"jagung tumis jamur asam manis\" adalah hidangan yang menggabungkan rasa manis dan asam dari saus dengan tekstur dan rasa jagung dan jamur yang renyah. Hidangan ini umumnya disajikan sebagai lauk pendamping nasi putih atau mi, dan dapat dimodifikasi dengan menambahkan bahan-bahan lain sesuai selera, seperti paprika atau tahu."},
        { "Sup Jagung","icon/makanan/Makan_Jagung_Sup","Sup jagung adalah hidangan sup yang utamanya terbuat dari bahan dasar jagung. Ini adalah hidangan yang umum dijumpai dalam berbagai budaya masakan di seluruh dunia.\r\n\r\n    Jagung: Jagung adalah tanaman serealia yang menghasilkan biji-bijian yang dapat dimakan. Dalam \"sup jagung,\" biji jagung umumnya digunakan baik dalam bentuk segar maupun dalam bentuk beku atau kalengan.\r\n\r\n    Bahan Tambahan: Selain jagung, \"sup jagung\" juga mungkin mengandung bahan-bahan tambahan seperti:\r\n\r\n        Sayuran: Sayuran lain seperti wortel, kentang, bawang bombay, atau seledri sering ditambahkan untuk memberikan variasi warna, rasa, dan tekstur dalam sup.\r\n\r\n        Kaldu: Sup biasanya dimasak dengan menggunakan kaldu sebagai cairan dasarnya. Kaldu bisa berbasis daging, sayuran, atau kaldu ayam.\r\n\r\n        Bumbu dan Rempah: Bumbu seperti garam, lada, dan bumbu-bumbu lainnya dapat ditambahkan untuk memberikan cita rasa yang sesuai. Beberapa resep sup jagung juga mungkin menggunakan bumbu seperti paprika, pala, atau bawang putih.\r\n\r\n    Cara Memasak: Dalam pembuatan \"sup jagung,\" bahan-bahan seperti jagung dan sayuran biasanya dipotong-potong dan dimasak dalam kaldu hingga matang. Proses memasak ini mungkin melibatkan merebus atau memasak dalam panci atau slow cooker.\r\n\r\n    Varian: Ada berbagai varian sup jagung di seluruh dunia. Beberapa mungkin mengandung bahan tambahan seperti daging ayam, daging sapi, atau seafood untuk memberikan protein tambahan. Ada juga variasi yang lebih kental dengan menggunakan tepung sebagai pengental sup.\r\n\r\n    Penyajian: Sup jagung umumnya disajikan panas dan sering dihidangkan sebagai hidangan pembuka dalam makanan utama.\r\n\r\nSup jagung adalah hidangan yang sederhana tetapi lezat, dan sering kali dianggap sebagai hidangan yang hangat dan nyaman, terutama pada musim dingin."},

        { "Cincin Bawang","icon/makanan/Makan_Bawang_Goreng","Cincin bawang adalah hidangan yang terbuat dari bawang bombai yang dipotong menjadi cincin tipis, dilapisi dengan adonan basah, dan kemudian digoreng. Cincin bawang biasanya disajikan dengan saus yang berbeda, seperti saus tomat, saus tartar, atau saus ranch.\r\n\r\nCincin bawang pertama kali dibuat di Amerika Serikat pada tahun 1930-an. Hidangan ini menjadi populer di tahun 1950-an dan 1960-an, dan sekarang menjadi hidangan populer di restoran dan bar di seluruh dunia.\r\n\r\nCincin bawang adalah makanan ringan yang populer, dan juga dapat disajikan sebagai lauk untuk makanan utama. Hidangan ini juga dapat dibuat di rumah, dan resepnya mudah ditemukan di internet."},

        { "Tumis Edamame","icon/makanan/Makan_Edamame_Tumis", "Edamame tumis adalah hidangan yang terbuat dari kacang edamame, sayuran, dan bumbu yang ditumis bersama. Kacang edamame adalah kacang hijau yang belum matang dan masih terbungkus kulitnya. Kacang edamame kaya akan protein, serat, dan nutrisi lainnya.\r\n\r\nEdamame tumis adalah hidangan yang sehat dan lezat. Hidangan ini dapat dinikmati sebagai makanan ringan, lauk, atau sebagai hidangan utama. Edamame tumis juga dapat menjadi sumber protein dan nutrisi yang baik bagi vegetarian dan vegan."},
        { "Edamame Goreng","icon/makanan/Makan_Edamame_Goreng" , "\"Edamame goreng\" adalah hidangan yang melibatkan edamame yang telah dikupas dan kemudian digoreng hingga renyah. Edamame adalah biji kedelai muda yang masih berada dalam bungkilnya dan sering dianggap sebagai camilan yang sehat dan kaya nutrisi.\r\n\r\n    Edamame: Edamame adalah biji kedelai yang masih muda dan sering dikenal karena kandungan protein dan serat yang tinggi. Edamame biasanya direbus atau dikukus, dan biji-biji tersebut dapat dikeluarkan dari bungkilnya sebelum dimakan.\r\n\r\n    Penggorengan: Dalam \"edamame goreng,\" biji edamame yang telah dikupas dari bungkilnya biasanya digoreng dalam minyak panas hingga berubah menjadi kecokelatan dan renyah. Proses penggorengan ini memberikan tekstur yang krispi pada biji edamame, mirip dengan tekstur kacang goreng.\r\n\r\n    Penyajian: Setelah digoreng, edamame goreng dapat disajikan sebagai camilan atau makanan ringan. Biasanya diberi sedikit garam atau bumbu lain sesuai selera untuk memberikan rasa yang lebih enak.\r\n\r\n    Varian: Selain disajikan dalam bentuk biji-biji, edamame goreng juga mungkin diolah lebih lanjut dengan menambahkan bumbu-bumbu seperti bawang putih, cabai, atau bumbu-bumbu khas tertentu untuk memberikan variasi cita rasa.\r\n\r\nEdamame goreng adalah camilan yang populer dalam berbagai budaya dan sering dijumpai di restoran Jepang atau restoran Asia lainnya. Hidangan ini memberikan rasa gurih, renyah, dan lezat, serta menyediakan alternatif camilan yang sehat."},

        { "Nasi Goreng Edamame","icon/makanan/Makan_NasiGoreng_edamame" , "\"Nasi goreng edamame\" adalah variasi dari hidangan nasi goreng yang mengandung edamame sebagai salah satu bahan utamanya.\r\n\r\n    Nasi Goreng: Nasi goreng adalah hidangan nasi yang dimasak dengan cara digoreng dalam wajan dengan berbagai bumbu dan bahan tambahan. Ini adalah hidangan yang umum ditemui dalam berbagai budaya masakan di seluruh dunia, terutama di Asia.\r\n\r\n    Edamame: Edamame adalah biji kedelai muda yang masih berada dalam bungkilnya. Biji ini sering dianggap sebagai camilan sehat dan mengandung protein serta serat yang tinggi.\r\n\r\nDalam \"nasi goreng edamame,\" edamame biasanya dimasukkan sebagai salah satu bahan utama dalam hidangan nasi goreng. Proses pembuatan nasi goreng edamame melibatkan memasak nasi putih yang telah dingin dengan minyak, bumbu-bumbu seperti bawang putih, bawang merah, dan saus kecap. Edamame yang telah dikupas dari bungkilnya kemudian ditambahkan ke dalam nasi goreng dan dicampur bersama dengan bahan-bahan lainnya.\r\n\r\nHasil akhir \"nasi goreng edamame\" adalah hidangan nasi yang memiliki cita rasa gurih dan renyah dari bumbu-bumbu nasi goreng, serta rasa gurih dan tekstur lezat dari edamame. Hidangan ini sering kali dihidangkan dengan tambahan bahan seperti daging ayam, udang, atau sayuran lainnya, dan dapat di atasinya dengan telur mata sapi atau irisan bawang putih goreng untuk memberikan variasi rasa dan tekstur.\r\n\r\n\"Nasi goreng edamame\" merupakan pilihan yang menarik bagi mereka yang ingin menambahkan protein dan nutrisi tambahan dalam hidangan nasi goreng, serta memberikan variasi yang menyegarkan pada rasa tradisional nasi goreng."},
        { "Nasi Goreng Jagung","icon/makanan/Makan_NasiGoreng_Jagung" , "\"Nasi goreng jagung\" adalah variasi dari hidangan nasi goreng yang mengandung jagung sebagai salah satu bahan utamanya.\r\n\r\n    Nasi Goreng: Nasi goreng adalah hidangan yang terbuat dari nasi yang digoreng dengan berbagai bumbu dan bahan tambahan. Ini adalah hidangan yang umum ditemui dalam berbagai budaya kuliner di seluruh dunia, terutama di Asia.\r\n\r\n    Jagung: Jagung adalah tanaman serealia yang menghasilkan biji-bijian yang umum dikonsumsi. Dalam \"nasi goreng jagung,\" biji jagung umumnya digunakan baik dalam bentuk segar, beku, atau kalengan.\r\n\r\nDalam \"nasi goreng jagung,\" biji jagung biasanya dimasukkan sebagai bahan tambahan dalam hidangan nasi goreng. Proses pembuatan nasi goreng jagung melibatkan memasak nasi putih yang telah dingin dengan minyak, bumbu-bumbu seperti bawang putih, bawang merah, dan saus kecap. Jagung kemudian ditambahkan ke dalam nasi goreng dan dicampur bersama dengan bahan-bahan lainnya.\r\n\r\nHasil akhir \"nasi goreng jagung\" adalah hidangan nasi yang memiliki cita rasa gurih dan renyah dari bumbu-bumbu nasi goreng, serta rasa manis dan tekstur kenyal dari jagung. Hidangan ini sering disajikan dengan tambahan bahan seperti potongan daging ayam, udang, atau sayuran lainnya. Dalam beberapa variasi, telur juga bisa dicampurkan ke dalam nasi goreng atau diletakkan di atasnya.\r\n\r\n\"Nasi goreng jagung\" adalah pilihan yang menarik bagi mereka yang ingin memberikan variasi dan kelezatan pada hidangan nasi goreng tradisional dengan tambahan tekstur dan rasa manis dari biji jagung."},

        { "Telur Rebus","icon/makanan/Makan_Telur_Rebus","\"Telur rebus\" adalah telur yang dimasak dengan cara merebus dalam air mendidih hingga matang.\r\n\r\n    Telur: Telur adalah bahan makanan yang sangat umum dan sering digunakan dalam berbagai hidangan. Telur memiliki kulit keras yang melindungi isinya, yang terdiri dari putih telur (albumen) dan kuning telur (kuning).\r\n\r\n    Cara Memasak: Untuk membuat \"telur rebus,\" telur biasanya direndam dalam air mendidih selama periode waktu tertentu tergantung pada tingkat kematangan yang diinginkan. Waktu perebusan yang berbeda akan menghasilkan hasil yang berbeda:\r\n\r\n        Telur Rebus Setengah Matang: Telur direbus dalam air mendidih selama beberapa menit, sehingga bagian putihnya matang tetapi kuning telur masih cair.\r\n\r\n        Telur Rebus Matang Setengah: Telur direbus dalam air mendidih selama lebih lama, sehingga bagian putih dan kuning telur semuanya telah matang tetapi kuning telur masih lembut dan sedikit kental.\r\n\r\n        Telur Rebus Matang Sempurna: Telur direbus dalam air mendidih lebih lama lagi hingga seluruh bagian putih dan kuning telur matang sepenuhnya.\r\n\r\n    Penggunaan: Telur rebus biasanya digunakan sebagai bahan makanan mandiri atau sebagai bagian dari hidangan lain. Mereka sering dijadikan camilan, bahan dalam salad, atau bahan dalam hidangan seperti telur rebus rendang, telur rebus balado, dan lain sebagainya.\r\n\r\n    Pentingnya Waktu Perebusan: Waktu perebusan memiliki dampak pada tekstur telur dan tingkat kekuningan kuning telur. Telur rebus dengan kuning telur yang masih lembut lebih umum disebut sebagai \"telur rebus setengah matang.\"\r\n\r\nTelur rebus adalah sumber protein yang baik dan sering digunakan dalam berbagai hidangan. Tingkat kematangan telur rebus bisa disesuaikan dengan preferensi masing-masing orang untuk mencapai cita rasa dan tekstur yang diinginkan." },
        { "Telur Ceplok","icon/makanan/Makan_Telur_Ceplok","\"Telor ceplok\" adalah istilah dalam bahasa Indonesia yang mengacu pada telur yang dimasak dengan cara digoreng dengan kuning telur yang masih cair. Telor ceplok juga dikenal dengan istilah \"telor mata sapi\" dalam beberapa daerah.\r\n\r\n    Telur Ceplok atau Telor Mata Sapi: Dalam \"telor ceplok,\" telur biasanya dipecahkan dan dituangkan ke dalam wajan yang sudah dipanaskan dengan minyak. Proses memasaknya melibatkan membiarkan telur menggoreng dengan panas sedang hingga bagian putih telur matang tetapi kuning telur masih cair dan tidak terganggu.\r\n\r\n    Cara Memasak: Untuk membuat telor ceplok, telur dipecahkan dengan hati-hati ke dalam wajan yang sudah panas. Pada saat yang tepat, telur dapat ditutupi untuk membantu memasak bagian atas kuning telur tanpa harus membalik telurnya.\r\n\r\n    Penggunaan: Telor ceplok umumnya disajikan sebagai lauk pendamping dalam hidangan seperti nasi goreng, nasi kuning, mi goreng, atau hidangan sarapan pagi lainnya. Telor ceplok juga bisa menjadi komponen dalam hamburger, sandwich, dan hidangan lainnya.\r\n\r\n    Variasi: Beberapa variasi dapat diterapkan pada telor ceplok, tergantung pada bagaimana seseorang ingin menikmatinya. Beberapa orang lebih suka kuning telur yang masih cair, sementara yang lain lebih suka kuning telur yang lebih matang. Beberapa juga menambahkan bumbu seperti garam dan lada saat memasak telor ceplok.\r\n\r\nTelor ceplok adalah hidangan sederhana tetapi populer yang sering menjadi bagian dari makanan sehari-hari. Konsistensi kuning telur yang masih cair memberikan rasa dan tekstur yang khas dalam hidangan." },
        { "Telur Dadar","icon/makanan/Makan_Telur_Gulung" , "\"Telur dadar\" adalah hidangan yang terbuat dari telur yang dikocok dan digoreng dalam wajan hingga matang. Istilah \"telur dadar\" digunakan dalam bahasa Indonesia untuk menggambarkan telur yang digoreng dalam bentuk datar.\r\n\r\n    Telur Dadar Sederhana: Dalam versi paling sederhana, telur dadar melibatkan mengocok telur dengan garam dan lada, lalu menuangkannya ke dalam wajan yang sudah dipanaskan dengan sedikit minyak. Telur kemudian digoreng hingga bagian atas dan bawahnya matang.\r\n\r\n    Variasi: Ada banyak variasi dalam pembuatan telur dadar tergantung pada preferensi rasa dan bahan yang digunakan. Beberapa variasi dapat mencakup:\r\n\r\n        Telur Dadar Isi: Telur dadar dapat diisi dengan bahan-bahan lain seperti keju, daging cincang, sayuran, atau bumbu lainnya sebelum digoreng.\r\n\r\n        Telur Dadar Bumbu: Bumbu-bumbu seperti bawang putih, cabai, atau rempah-rempah lainnya juga dapat ditambahkan ke dalam telur dadar untuk memberikan cita rasa tambahan.\r\n\r\n        Telur Dadar Kekuningan: Beberapa orang lebih suka membuat telur dadar dengan kuning telur yang masih sedikit cair di tengahnya.\r\n\r\n    Penggunaan: Telur dadar sering kali dihidangkan sebagai hidangan sederhana yang bisa menjadi lauk pendamping dalam makanan seperti nasi goreng, nasi kuning, mi goreng, atau hidangan lainnya. Telur dadar juga bisa dijadikan komponen dalam sandwich, burger, atau wrap.\r\n\r\n    Fleksibilitas dan Popularitas: Telur dadar adalah hidangan yang sederhana tetapi serbaguna. Dapat dimodifikasi dengan berbagai bahan dan bumbu sesuai dengan selera, dan sering menjadi pilihan hidangan cepat yang populer untuk berbagai kesempatan makan."},

        { "Nasi Goreng Lengkap","icon/makanan/Makan_NasiGoreng_Telur","Nasi Goreng lengkap adalah hidangan nasi yang digoreng dengan bumbu-bumbu dan bahan tambahan. Ini adalah hidangan populer di banyak budaya kuliner, terutama di Asia.\r\n\r\n Dalam \"nasi goreng lengkap,\" nasi yang telah dingin dimasak bersama dengan berbagai bahan tambahan untuk menciptakan hidangan yang lebih beragam. Bahan-bahan yang sering digunakan dalam nasi goreng lengkap termasuk:\r\n\r\n        Telur: Telur biasanya digoreng terpisah atau diintegrasikan dengan nasi goreng, baik sebagai telur mata sapi atau telur dadar.\r\n\r\nSayuran: Berbagai jenis sayuran seperti wortel, kacang polong, bawang hijau, bawang merah, dan lain-lain bisa digunakan untuk memberikan rasa dan warna yang beragam.\r\n\r\n        Saus dan Bumbu: Bumbu-bumbu seperti bawang putih, saus kecap, saus cabai, dan bumbu lainnya digunakan untuk memberikan cita rasa khas nasi goreng.\r\n\r\n    Penyajian: Nasi goreng lengkap disajikan sebagai hidangan utama yang berdiri sendiri. Hidangan ini bisa dihias dengan irisan mentimun, tomat, atau telur rebus untuk memberikan tampilan yang lebih menarik.\r\n\r\n    Variasi: Karena nasi goreng lengkap dapat disesuaikan dengan berbagai bahan sesuai selera, ada banyak variasi dalam bahan dan rasa yang mungkin tergantung pada tradisi dan preferensi lokal.\r\n\r\n\"Nasi goreng lengkap\" adalah pilihan yang populer untuk mereka yang ingin menikmati hidangan yang beragam dan mengenyangkan. Keberagaman bahan dan rasa membuatnya menjadi hidangan yang lezat dan memuaskan untuk dinikmati sebagai makanan utama." }
    };
    public static string[,] arrayResep =
    { // 1 ke kanan, 0 ke bawah
        { "Pokchoi Siram Jamur", "icon/makanan/Makan_Pokchoi_Jamur", "Pokchoi x1\nBawang x1\nJamur x1\nKecap x1"},
        { "Pokchoi Saus Tiram", "icon/makanan/Makan_Pokchoi_SausTiram","Pokchoi x1\nBawang x1\nKecap x1\nSaus Tiram x1"},
        { "Tumis Pakchoi Tahu", "icon/makanan/Makan_Pokchoi_Tahu","Pokchoi x1\nBawang x1\nSaus Tiram x1\nTahu x1\nCabai"},
        
        { "Tumis Selada Jamur", "icon/makanan/Makan_Selada_TumisJamur", "Selada x1\n Bawang x1 \n Jamur x1\n Kecap x1"},
        { "Telur Dadar Selada","icon/makanan/Makan_Selada_TelurGulung","Selada x1\n Telur x1\n Kecap x1\n Margarin x1"},

        { "Kangkung Tempe","icon/makanan/Makan_Kangkung_TumisTempe","Kangkung x1 \n Bawang x1 \n Saus Tiram x1 \n Tempe x1" },
        { "Cah Kangkung","icon/makanan/Makan_Kangkung_Tumis","Kangkung x1 \n Bawang x1 \n Saus Tiram x1\n Cabai x1"},

        { "Jagung Bakar", "icon/makanan/Makan_Jagung_Bakar","Jagung x1\n Margarin x1" },
        { "Tumis Jagung Bakar","icon/makanan/Makan_Jagung_Tumis","Jagung Bakar x1\n Bawang x1\n Cabai x1" },
        { "Jagung Jamur Asam Manis","icon/makanan/Makan_Jagung_SiramJamur","Jagung x1 \n Jamur x1 \n Saus Tiram x1 \n Cabai x1 \n"},
        { "Sup Jagung","icon/makanan/Makan_Jagung_Sup","Jagung x1 \n Bawang x1 \n Telur x1 \n Tepung x1"},

        { "Cincin Bawang","icon/makanan/Makan_Bawang_Goreng","Bawang x1 \n Tepung x1 \n Minyak x1"},

        { "Tumis Edamame","icon/makanan/Makan_Edamame_Tumis", "Edamame x1 \n Bawang x1 \n Kecap x1 \n Margarin x1"},
        { "Edamame Goreng","icon/makanan/Makan_Edamame_Goreng" , "Edamame x1 \n Bawang x1 \n Minyak x1 \n"},

        { "Nasi Goreng Edamame","icon/makanan/Makan_NasiGoreng_edamame" , "Nasi x1 \n Edamame x1 \n Bawang x1 \n Kecap x1 \n Cabai x1 \n Minyak x1"},
        { "Nasi Goreng Jagung","icon/makanan/Makan_NasiGoreng_Jagung" , "Nasi x1 \n Jagung x1 \n Bawang x1 \n Kecap x1 \n Cabai x1 \n Minyak x1"},

        { "Telur Rebus","icon/makanan/Makan_Telur_Rebus","Telur x1" },
        { "Telur Ceplok","icon/makanan/Makan_Telur_Ceplok","Telur x1 \n Minyak x1" },
        { "Telur Dadar","icon/makanan/Makan_Telur_Gulung" , "Telur x1 \n Bawang x1 \n Minyak x1 \n Saus Tiram x1"},

        { "Nasi Goreng Lengkap","icon/makanan/Makan_NasiGoreng_Telur","Nasi x1 \n Tumis Pokchoi Tahu x1 \n Selada x1 \n Kangkung x1 \n Jagung x1 \n Edamame x1 \n Bawang x1 \n Telur x1 \n Jamur x1 \n Kecap x1 \n Saus Tiram x1 \n Cabai x1 \n Minyak x1 \n" }
    };
    public static string[][] arrayIngredient =
    {
        new string[]
            {"Pokchoi","Bawang","Jamur","Kecap"},
        new string[]
            {"Pokchoi","Bawang","Kecap","SausTiram"},
        new string[]
            {"Pokchoi","Bawang","SausTiram","Tahu","Cabai"},

        new string[]
            {"Selada","Bawang","Jamur","SausTiram"},
        new string[]
            {"Selada","Telur","Kecap","Margarin"},

        new string[]
            {"Kangkung","Bawang","SausTiram","Tempe"},
        new string[]
            {"Kangkung","Bawang","SausTiram","Cabai"},

        new string[]
            {"Jagung","Margarin"},
        new string[]
            {"Jagung Bakar","Bawang","Cabai"},
        new string[]
            {"Jagung","Bawang","Jamur","SausTiram","Cabai"},
        new string[]
            {"Jagung","Bawang","Telur","Tepung"},
        
        new string[]
            {"Bawang","Tepung","Minyak"},
        
        new string[]
            {"Edamame","Bawang","Kecap","Cabai"},
        new string[]
            {"Edamame","Bawang","Minyak"},

        new string[]
            {"Nasi","Edamame","Bawang","Kecap","Cabai","Minyak"},
        new string[]
            {"Nasi","Jagung","Bawang","Kecap","Cabai","Minyak"},

        new string[]
            {"Telur"},
        new string[]
            {"Telur","Minyak"},
        new string[]
            {"Telur","Bawang","SausTiram","Minyak"},
        
        new string[]
            {"Nasi","Tumis Pokchoi Tahu","Selada","Kangkung Tempe","Jagung","Edamame","Bawang","Telur Ceplok","Jamur","Kecap","SausTiram","Cabai","Minyak"}


    };
    public static string[,] arrayMarket =
    { // 1 ke kanan, 0 ke bawah
        { "Telur", "icon/bahan/Telur", "50G" },
        { "Jamur", "icon/bahan/Jamur", "100G" },
        { "Kecap", "icon/bahan/Kecap", "20G" },
        { "SausTiram", "icon/bahan/SausTiram", "50G" },
        { "Tahu", "icon/bahan/Tahu", "100G" },
        { "Tempe", "icon/bahan/Tempe", "20G" },
        { "Cabai", "icon/bahan/Cabai", "50G" },
        { "Margarin", "icon/bahan/Butter", "100G" },
        { "Tepung", "icon/bahan/Tepung", "20G" },
        { "Minyak", "icon/bahan/Minyak", "20G" }

    };


    public static int pupukBuff = 100;
}